version: '3.7'

services:
  app:
    image: 'final:latest'
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: aplikacja
    restart: always
    depends_on:
      - postgresql
    ports:
      - 8080:8080
    networks:
      - app-net

  postgresql:
    image: postgres
    container_name: postgresqll
    restart: always
    ports:
      - "5433:5432"
    networks:
      - app-net
    environment:
      - 'POSTGRES_ROOT_PASSWORD=#Password'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=#Password'

networks:
  app-net:
    driver: bridge

